feat(aliases): add proxy handling for code-insiders and notification functions

diff --git a/bash/iac_aliases b/bash/iac_aliases
--- a/bash/iac_aliases
+++ b/bash/iac_aliases
@@ -31,9 +31,44 @@ function iac-replace {
 # Replace all versions with target version
 function iac-replace-all {
 	target_version="$1"
-	
-	for v in $(wgrep "\s*source\s*=\s*" | cut -d\? -f2- | sort | uniq | cut -d = -f2- | sed 's|"||'); do 
+
+	echo "Replacing all versions with $target_version: $*"
+
+	for v in $(wgrep "\s*source\s*=\s*" | cut -d\? -f2- | sort | uniq | cut -d = -f2- | sed 's|"||'); do
 		iac-replace "$v" "$target_version"
+	done
+}
+
+# Replace version with target version for a file
+function iac-replace-file {
+	local -r original="$1"
+	local -r new="$2"
+	local -r file="$3"
+	local -r auto_approve="${4:-false}"
+
+	echo -e "Replacing '$original' with '$new' in '$file':\n"
+	if ! grep "$original" "$file"; then
+		echo "Found nothing to replace."
+		return 1
+	fi
+	echo
+
+	if [[ "$auto_approve" == "false" ]] && ! ask "Do you want to proceed with replacement?"; then
+		return 1
+	fi
+
+	sed -i -e "s|${original}|${new}|g" "$file" &&
+		echo -e "\n✔️  Replaced '$original' with '$new' in '$file'" || echo -e "\n❌  Failed to replace '$original' with '$new' in '$file'"
+}
+
+# Replace versions with target version for files provided
+function iac-replace-files {
+	target_version="$1"
+	shift
+
+	for f in "$@"; do
+		v="$(grep "\s*source\s*=\s*" "$f" | cut -d\? -f2- | sort | uniq | cut -d = -f2- | sed 's|"||')"
+		iac-replace-file "$v" "$target_version" "$f"
 	done
 }
 
