style(shfmt): format

diff --git a/bash/log_aliases b/bash/log_aliases
--- a/bash/log_aliases
+++ b/bash/log_aliases
@@ -2,45 +2,45 @@
 
 # Echo to stderr. Useful for printing script usage information.
 function echo_stderr {
-  >&2 echo "$@"
+	>&2 echo "$@"
 }
 
 # Log the given message at the given level. All logs are written to stderr with a timestamp.
 function log {
-  local -r level="$1"
-  local -r message="$2"
-  local -r debug_enabled="${3:-false}"
-  local -r timestamp=$(date +"%Y-%m-%d %H:%M:%S")
-  local -r script_name="$(basename "$0")"
+	local -r level="$1"
+	local -r message="$2"
+	local -r debug_enabled="${3:-false}"
+	local -r timestamp=$(date +"%Y-%m-%d %H:%M:%S")
+	local -r script_name="$(basename "$0")"
 
-  if [[ "$level" = "DEBUG" ]] && [[ "$debug_enabled" != "true" ]]; then
-    return
-  fi
+	if [[ "$level" = "DEBUG" ]] && [[ "$debug_enabled" != "true" ]]; then
+		return
+	fi
 
-  echo_stderr -e "${timestamp} [${level}] [$script_name] ${message}"
+	echo_stderr -e "${timestamp} [${level}] [$script_name] ${message}"
 }
 
 # Log the given message at INFO level. All logs are written to stderr with a timestamp.
 function log_info {
-  local -r message="$1"
-  log "INFO" "$message"
+	local -r message="$1"
+	log "INFO" "$message"
 }
 
 # Log the given message at WARN level. All logs are written to stderr with a timestamp.
 function log_warn {
-  local -r message="$1"
-  log "WARN" "$message"
+	local -r message="$1"
+	log "WARN" "$message"
 }
 
 # Log the given message at ERROR level. All logs are written to stderr with a timestamp.
 function log_error {
-  local -r message="$1"
-  log "ERROR" "$message"
+	local -r message="$1"
+	log "ERROR" "$message"
 }
 
 # Log the given message at DEBUG level. All logs are written to stderr with a timestamp.
 function log_debug {
-  local -r message="$1"
-  local -r debug_enabled="${2:-false}"
-  log "DEBUG" "$message" "$debug_enabled"
+	local -r message="$1"
+	local -r debug_enabled="${2:-false}"
+	log "DEBUG" "$message" "$debug_enabled"
 }
